os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      osx_image: xcode7.3
      compiler: clang

language: cpp

addons:
apt:
  packages:
  - gfortran
  - libglu1-mesa-dev
  - libgl1-mesa-dev
  - libmpich2-dev

env:
  - WITH_CMAKE=true BUILD_VTK=true
  - WITH_CMAKE=true BUILD_VTK=false
matrix:
 allow_failures:
  - env: WITH_CMAKE=true BUILD_VTK=false

git:
  submodules: false

before_install:
  - export NUM_THREADS=4
  - export cwd=$(pwd)
  - export SCRIPTS=$cwd/travis
  - export BUILD_DIR=$cwd/build
  - export SV_TOP_DIR=$cwd
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"; fi

cache:
  directories:

before_script:
  - $SCRIPTS/travis_before_script_cleanup.sh
  #- if ! $WITH_CMAKE; then $ fi

script: $SCRIPTS/travis_build.sh

