os:
  - linux
  - osx

compiler:
  - gcc
  - clang

dist:
  - trusty

osx_image:
  - xcode7.3

sudo:
  - required

addons:
apt:
  packages:
  - gfortran
  - libglu1-mesa-dev
  - libgl1-mesa-dev
  - libmpich2-dev

language: cpp

env:
  - WITH_CMAKE=true BUILD_VTK=true
  - WITH_CMAKE=true BUILD_VTK=false
matrix:
 allow_failures:
  - env: WITH_CMAKE=true BUILD_VTK=false

git:
  submodules: false

before_install:
  - export NUM_THREADS=4
  - export cwd=$(pwd)
  - export SCRIPTS=$cwd/travis
  - export BUILD_DIR=$cwd/build
  - export SV_TOP_DIR=$cwd

cache:
  directories:

before_script:
  - $SCRIPTS/travis_before_script_cleanup.sh
  #- if ! $WITH_CMAKE; then $ fi

script: $SCRIPTS/travis_build.sh

