dist: trusty
sudo: required

env:
  - WITH_CMAKE=true BUILD_VTK=true

language: cpp

compiler: gcc

install:

addons:
  apt:
    packages:
    - gfortran
    - libglu1-mesa-dev
    - libgl1-mesa-dev
    - libmpich2-dev

git:
  submodules: false

before_install:
  - export NUM_THREADS=4
  - export cwd=$(pwd)
  - export SCRIPTS=$cwd/travis
  - $SCRIPTS/travis_before_script_cleanup.sh
  - export BUILD_DIR=$cwd/build
  - export SV_TOP_DIR=$cwd
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

cache:
  directories:

before_script:
  - $SCRIPTS/travis_before_script_cleanup.sh
  #- if ! $WITH_CMAKE; then $ fi

script: $SCRIPTS/travis_build.sh

