language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: WITH_CMAKE=true BUILD_VTK=false
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: WITH_CMAKE=true BUILD_VTK=true
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      sudo: required
      env: WITH_CMAKE=true BUILD_VTK=false
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      sudo: required
      env: WITH_CMAKE=true BUILD_VTK=true
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
      - gfortran
      - libglu1-mesa-dev
      - libgl1-mesa-dev
      - libmpich2-dev

git:
  submodules: false

before_install:
  - export NUM_THREADS=4
  - export cwd=$(pwd)
  - export SCRIPTS=$cwd/travis
  - export BUILD_DIR=$cwd/build
  - export SV_TOP_DIR=$cwd
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpich; fi

script: $SCRIPTS/travis_build.sh
